# These configs are general configs that don't fit any other category.
[general]

	# Set to true to pause the server when all players are paused.
	pauseWhenAllPlayersPaused = true

	# Set to true to pause the server when no players are connected.
	pauseWhenNoPlayers = true

	# Set to true to send a chat message to all players when the server pause state changes.
	sendChatMessageWhenPauseStateChanges = false

	# Set to true to send a chat message to all players (and to the server log) when the a player's pause state changes.
	sendChatMessageWhenPlayerPauseStateChanges = false

	# Permission level required to use the op commands for Multiplayer Server Pause
	# Range: Go wild, but not too wild
	commandPermissionLevel = 4

	# Disables these mod compatibilities if any errors occur with them turned on. Accepts: valkyrienSkies
	disabledCompatibilities = []

